%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [1.00000000000000000, 0.00000000000000000, 0.00000000000000000, -0.04889999999999999858]
    - [0.00000000000000000, -1.00000000000000000, 0.00000000000000000, 0.00185000000000000009]
    - [0.00000000000000000, 0.00000000000000000, -1.00000000000000000, -0.00533999999999999986]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.28986358642578125, 0.07100677490234375, -0.00037384033203125, 0.00028610229492188]
  distortion_model: radtan
  intrinsics: [705.14129638671875000,  706.42608642578125000, 635.06823730468750000, 349.81445312500000000] #fu, fv, cu, cv
  resolution: [1280, 720]
  rostopic: /mynteye/left/image_color


cam1:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [0.999966621398926,      -0.00333428382873535,      -0.00744748115539551,   0.0711155633116447]
    - [-0.00332427024841309,        -0.999993443489075,       0.00137102603912354, 0.00145102251622629]
    - [-0.00745201110839844,      -0.00134623050689697,        -0.999971270561218, -0.00623438716437144]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole     
  distortion_coeffs: [-0.28271865844726562, 0.06465911865234375, -0.00004959106445312, -0.00108718872070312]
  distortion_model: radtan
  intrinsics: [704.27484130859375000, 705.84533691406250000, 666.35815429687500000, 346.86102294921875000] #fu, fv, cu, cv
  resolution: [1280, 720]
  rostopic: /mynteye/right/image_color
